config/routes.rb
Rails.application.routes.draw do
  resources :pages
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :expenses
 

  root 'pages#home'
  get '/contact', :to => 'pages#contact'
  get '/about',   :to => 'pages#about'
  get '/help',    :to => 'pages#help'
  get '/signup',  :to => 'users#new'
  get '/signin',  :to => 'sessions#new'
  get '/signout', :to => 'sessions#destroy'

end

app/views/pages/home.html.erb
<% if signed_in? %>
  <%= form_tag expenses_path, :method => :get do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search" %>  
    </p>
  <% end %>
  <div id="container" style="width:800px; height:200px;"></div>
      <tr>      
        <h1 class="expense">Welcome To Spendify</h1> 
        <table class="table table-striped" style="border:1px solid black;">
          <tr>
          <th>Date</th> 
          <th>Merchant</th>
          <th>Comment</th>
          <th>Category</th>
          <th>Total Amount (NPR)</th>
          <th>Payment Mode (Reimbursable or Billable)</th> 
          <th>Edit</th>
          <th>Email</th>
          </tr>
          <%= render @expenses %>
        </table>
          <div class="container">
            <%= link_to 'New Expense', new_expense_path %></button>
          </div>  
<% else %>
  <h1>Spendify App</h1>
  <b><%= link_to "Sign up now!", signup_path, :class => "signup_button round" %></b>
<% end %>

<script type="text/javascript">
  $(function (){
    $('#container').highcharts({
      chart: {
        type: 'column'
      },
      title: {
        text: 'Users Expenses'
      },
      xAxis: {
          categories: 
          <%= raw @expenses.map{|expense|  expense.category } %>
      },
      yAxis: {
          title: {
              text: 'Amount (NPR)'
          }
      },
      series: [{
              name: 'Merchant',
              data: <%= @expenses.map do |expense| expense.total end %>
      }]  
    });
  });
</script>

app/views/pages/new.html.erb
<h1>New Page</h1>
<%= render 'form' %>
<button><%= link_to 'Back', pages_path %></button>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>
<button><%= link_to 'Edit', edit_page_path(@page) %><button> |
<button><%= link_to 'Back', pages_path %><button>